Feature/image formatting
antaliadom-team/backend pull request #148
Opened 2023-02-28 07:38 UTC by kultmet

2023-02-28 07:43 UTC, kultmet commented
Существует баг. При Апдейте конкретного объекта Image, дополнительная фотка не удаляется.
Проблема решения этого вопроса связана с тем, что метода update у класса модели нет, а в методе save (при редактировании) я не могу найти имя предыдущего файла.

2023-02-28 13:36 UTC, spaut33 requested changes

2023-02-28 13:36 UTC, spaut33 commented on antalia_project/constants.py
> +PREVIEW_SIZE = (328, 261)
```suggestion
# Список размеров в пикселях создаваемых превью для фотографий объекта [(hor, vert), ...]
PREVIEW_SIZES = [(328, 261), (738, 632)]
```

2023-02-28 13:36 UTC, spaut33 commented on antalia_project/constants.py
> +PREVIEW_SIZE = (328, 261)
эту константу и выше можно убрать

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +    return (f'real_estate/{id}_'
```suggestion
    return (f'real_estate/{instance.real_estate.pk}_'
```

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +            f'{datetime.timestamp(datetime.now())*1000:.0f}.jpg')
```suggestion
            f'{datetime.now().timestamp()*1000:.0f}.jpg')
```

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +    id = instance.real_estate.pk
лишняя переменная, потому что одноразовая

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +                    (0, 0 + height // 5, width, height - height // 5)
я все еще не понимаю, для чего мы тут кропаем вертикальные фотографии. Это надо делать в создании превьюшки.

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +            outfile = self.filename_generator(self.image.path, size)
лишняя переменная, потому что одноразовая. Лучше подставить сразу расчет в image_generator

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +        weith, higth = size
переведи плиз на английский нормально, выше у тебя правильно написано

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +        for size in settings.ALL_SIZES:
тут будет другая константа: PREVIEW_SIZES
```suggestion
        for size in settings.PREVIEW_SIZES:
```

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +                infile=infile,
тут тоже лучше сразу подставить self.image

2023-02-28 13:36 UTC, spaut33 commented on catalog/models.py
> +        infile = self.image
лишняя переменная, потому что одноразовая

2023-02-28 18:33 UTC, spaut33 commented on catalog/models.py
> +                    (0, 0 + height // 5, width, height - height // 5)
Написал в дискорде, такой вариант не годится, не по ТЗ

2023-03-01 10:41 UTC, kultmet commented
еее маза фака

2023-03-03 08:24 UTC, spaut33 requested changes

2023-03-03 08:24 UTC, spaut33 commented on catalog/models.py
> +                os.remove(self.filename_generator(self.image.path, size))
Неэффективность. Два раза вычисляется имя одного и того же файла. Здесь как раз наоборот надо вычисление вынести в переменную и подставить переменную в path.exists и os.remove

2023-03-12 07:30 UTC, spaut33 approved these changes

2023-03-12 07:30 UTC, merged