Added activation for users with Djoser
antaliadom-team/backend pull request #189
Opened 2023-04-05 05:40 UTC by kultmet

2023-04-09 08:01 UTC, spaut33 requested changes
config.py старый, нужно подтянуть обязательно актуальный из dev и править его
ACTIVATION_URL давай заменим на 'activate/{uid}/{token}',

2023-04-09 08:53 UTC, kultmet commented
Рома, я не совсем понял

2023-04-09 08:55 UTC, spaut33 commented
> Рома, я не совсем понял

ты не спулил актуальную ветку и начал править старый вариант config.py, сравни что у тебя и что в ветке dev сейчас

2023-04-09 09:00 UTC, kultmet commented
Давай в дискорд. У меня активационный юрл такой же как ты требуешь

2023-04-17 14:42 UTC, spaut33 commented
up

2023-04-18 17:00 UTC, closed without merging