Фильтрация
antaliadom-team/backend pull request #77
Opened 2023-02-07 21:32 UTC by pencool

добавил фильтрацию объектов и фильтрацию объектов по избранному

2023-02-07 22:02 UTC, spaut33 requested changes

2023-02-07 22:02 UTC, spaut33 commented on catalog/filters.py
> +    rooms = filters.NumberFilter()
По ТЗ количество комнат в фильтре задается так: 1, 2, 3, 4+, при последнем значении с фронта придет 4, а нам нужно выбирать все объекты, в которых количество комнат >= 4. Этот момент нужно предусмотреть.
![image](https://user-images.githubusercontent.com/5065694/217376472-af9a2a35-7186-43b6-a643-585173ff510e.png)

2023-02-08 07:11 UTC, pencool commented on catalog/filters.py
> +    rooms = filters.NumberFilter()
ок, буду дома поправлю

2023-02-08 21:22 UTC, spaut33 approved these changes

2023-02-08 21:23 UTC, merged